#!/usr/bin/env python3
"""Generate fast logic gate variants and their icon overlays."""

from __future__ import annotations

import json
from pathlib import Path

from PIL import Image, ImageDraw

ROOT = Path(__file__).resolve().parent
SHAPESET_PATH = ROOT / "Objects/Database/ShapeSets/fastlogicgates.shapeset"
LUA_PATH = ROOT / "Scripts/fastLogicBlocks/FastLogicGateColors.lua"
OVERLAY_MANIFEST_PATH = ROOT / "Gui/IconOverlays_FastLogicGates.json"
OVERLAY_DIR = ROOT / "Gui/FastLogicGateOverlays"

SHAPE_COLOR = "df7f01"
UUID_SUFFIX_START = 88087
DEFAULT_GATE_INDEX = 25
OVERLAY_SIZE = 96
CIRCLE_DIAMETER = 30
CIRCLE_MARGIN = 5
ANTIALIAS_SCALE = 4

COLORS = [
    ("eeeeee", "ffffff"),
    ("7f7f7f", "8b8b8b"),
    ("4a4a4a", "515151"),
    ("222222", "252525"),
    ("f5f071", "ebff75"),
    ("e2db13", "d7f814"),
    ("817c00", "798d00"),
    ("323000", "2f3700"),
    ("cbf66f", "b9ff73"),
    ("a0ea00", "80ff00"),
    ("577d07", "488907"),
    ("375000", "2c5800"),
    ("68ff88", "68ffa3"),
    ("19e753", "1bfe84"),
    ("0e8031", "0f8c4c"),
    ("064023", "064631"),
    ("7eeded", "87e9ff"),
    ("2ce6e6", "30d8fd"),
    ("118787", "127d94"),
    ("0a4444", "0b3f4a"),
    ("4c6fe3", "535cf9"),
    ("0a3ee2", "0a19f8"),
    ("0f2e91", "10189f"),
    ("0a1d5a", "0b1063"),
    ("ae79f0", "cf80ff"),
    ("7514ed", "a715ff"),
    ("500aa6", "760ab6"),
    ("35086c", "4e0876"),
    ("ee7bf0", "ff82ea"),
    ("cf11d2", "e712c4"),
    ("720a74", "7f0b6c"),
    ("520653", "5b064d"),
    ("f06767", "ff876d"),
    ("d02525", "e44a28"),
    ("7c0000", "881800"),
    ("560202", "5e1202"),
    ("eeaf5c", "ffd762"),
    ("df7f00", "f5b700"),
    ("673b00", "715500"),
    ("472800", "4e3a00"),
]


def gate_uuid(index: int) -> str:
    return f"6a9dbff5-7562-4e9a-99ae-3590ece{UUID_SUFFIX_START + index}"


def write_shapeset() -> None:
    parts = []
    for index in range(len(COLORS)):
        parts.append(
            {
                "box": {"x": 1, "y": 1, "z": 1},
                "color": SHAPE_COLOR,
                "name": "Fast Logic Gate",
                "physicsMaterial": "Mechanical",
                "ratings": {
                    "density": 2,
                    "durability": 3,
                    "friction": 5,
                    "buoyancy": 2,
                },
                "renderable": (
                    "$CONTENT_DATA/Renderable/otherRends/fast_logic_gate.rend"
                ),
                "rotationSet": "PropYZ",
                "scripted": {
                    "classname": f"FastLogicGate_{index}",
                    "filename": (
                        "$CONTENT_DATA/Scripts/fastLogicBlocks/FastLogicGateColors.lua"
                    ),
                },
                "uuid": gate_uuid(index),
                "showInInventory": index == DEFAULT_GATE_INDEX,
            }
        )
    SHAPESET_PATH.write_text(
        json.dumps({"partList": parts}, indent=4) + "\n", encoding="utf-8"
    )


def write_lua() -> None:
    lines = [
        "-- Generated by generate_fast_logic_gates.py.",
        'dofile "FastLogicGate.lua"',
        "",
    ]
    for index, (normal, highlight) in enumerate(COLORS):
        lines.extend(
            [
                (
                    f"FastLogicGate_{index} = table.deepCopyTo(FastLogicGate, "
                    f"(FastLogicGate_{index} or class()))"
                ),
                f"FastLogicGate_{index}.colorNormal = sm.color.new(0x{normal}ff)",
                f"FastLogicGate_{index}.colorHighlight = sm.color.new(0x{highlight}ff)",
            ]
        )
    LUA_PATH.write_text("\n".join(lines) + "\n", encoding="utf-8")


def make_circle(color: str) -> Image.Image:
    scaled_size = OVERLAY_SIZE * ANTIALIAS_SCALE
    image = Image.new("RGBA", (scaled_size, scaled_size), (0, 0, 0, 0))
    left = (OVERLAY_SIZE - CIRCLE_MARGIN - CIRCLE_DIAMETER) * ANTIALIAS_SCALE
    top = CIRCLE_MARGIN * ANTIALIAS_SCALE
    right = left + CIRCLE_DIAMETER * ANTIALIAS_SCALE - 1
    bottom = top + CIRCLE_DIAMETER * ANTIALIAS_SCALE - 1
    ImageDraw.Draw(image).ellipse((left, top, right, bottom), fill=f"#{color}")
    return image.resize((OVERLAY_SIZE, OVERLAY_SIZE), Image.Resampling.LANCZOS)


def write_overlays() -> None:
    OVERLAY_DIR.mkdir(parents=True, exist_ok=True)
    for path in OVERLAY_DIR.glob("connection_*.png"):
        path.unlink()

    overlays = []
    for index, (normal, _) in enumerate(COLORS):
        image_name = f"connection_{normal}.png"
        make_circle(normal).save(OVERLAY_DIR / image_name, optimize=True)
        overlays.append(
            {
                "image": f"FastLogicGateOverlays/{image_name}",
                "icons": [gate_uuid(index)],
            }
        )

    OVERLAY_MANIFEST_PATH.write_text(
        json.dumps({"overlays": overlays}, indent=4) + "\n", encoding="utf-8"
    )


def main() -> None:
    write_shapeset()
    write_lua()
    write_overlays()
    print(f"Generated {len(COLORS)} fast logic gate variants and icon overlays.")


if __name__ == "__main__":
    main()
