#!/usr/bin/env python3
"""Generate the curved connection tube renderables and their registries."""

from __future__ import annotations

import json
import math
import uuid
from pathlib import Path

START_LENGTH = 0.25
MAX_LENGTH = 1024.0
LENGTH_RATIO = 1.2
BOW_RATIO = 0.15
TUBE_RADIUS = 0.008
CURVE_SEGMENTS = 32
TUBE_SIDES = 8
UUID_NAMESPACE = uuid.UUID("65c31d20-123f-46c9-8974-8d548babd8de")

ROOT = Path(__file__).resolve().parents[2]
CURVE_ROOT = ROOT / "Renderable" / "curve_tubes"
MODEL_DIR = CURVE_ROOT / "Models"
REND_DIR = CURVE_ROOT / "Rends"
SHAPESET_PATH = ROOT / "Objects" / "Database" / "ShapeSets" / "display.shapeset"
LUA_PATH = ROOT / "Scripts" / "NewTool" / "CurveTubeModels.lua"
RENDERABLE_PREFIX = "$CONTENT_DATA/Renderable/curve_tubes/Rends/curve_tube_"


def tier_lengths() -> list[float]:
    values = []
    value = START_LENGTH
    while value < MAX_LENGTH:
        values.append(value)
        value *= LENGTH_RATIO
    values.append(MAX_LENGTH)
    return values


def tier_uuid(index: int, length: float) -> str:
    name = f"curve-tube:{index}:{length:.9f}"
    return str(uuid.uuid5(UUID_NAMESPACE, name))


def center_and_frame(length: float, t: float):
    bow = length * BOW_RATIO
    one_minus_t = 1.0 - t
    x = 4.0 * bow * t * one_minus_t
    y = length * (t - 0.5)

    dx = 4.0 * bow * (1.0 - 2.0 * t)
    dy = length
    tangent_length = math.hypot(dx, dy)
    normal = (dy / tangent_length, -dx / tangent_length, 0.0)
    binormal = (0.0, 0.0, 1.0)
    return (x, y, 0.0), normal, binormal


def generate_obj(length: float) -> str:
    vertices = []
    normals = []
    uvs = []

    for curve_index in range(CURVE_SEGMENTS + 1):
        t = curve_index / CURVE_SEGMENTS
        center, normal, binormal = center_and_frame(length, t)
        for side_index in range(TUBE_SIDES):
            angle = math.tau * side_index / TUBE_SIDES
            radial = (
                math.cos(angle) * normal[0] + math.sin(angle) * binormal[0],
                math.cos(angle) * normal[1] + math.sin(angle) * binormal[1],
                math.cos(angle) * normal[2] + math.sin(angle) * binormal[2],
            )
            vertices.append(tuple(center[i] + TUBE_RADIUS * radial[i] for i in range(3)))
            normals.append(radial)
            uvs.append((side_index / TUBE_SIDES, t))

    lines = [
        "# Generated by generate_curve_tubes.py",
        f"# Base endpoint distance: {length:.9f}",
        "o CurvedConnectionTube",
    ]
    lines.extend(f"v {x:.9f} {y:.9f} {z:.9f}" for x, y, z in vertices)
    lines.extend(f"vt {u:.9f} {v:.9f}" for u, v in uvs)
    lines.extend(f"vn {x:.9f} {y:.9f} {z:.9f}" for x, y, z in normals)
    lines.append("s 1")
    lines.append("usemtl ConnectionTube")

    for curve_index in range(CURVE_SEGMENTS):
        row = curve_index * TUBE_SIDES
        next_row = (curve_index + 1) * TUBE_SIDES
        for side_index in range(TUBE_SIDES):
            next_side = (side_index + 1) % TUBE_SIDES
            indices = (
                row + side_index + 1,
                row + next_side + 1,
                next_row + next_side + 1,
                next_row + side_index + 1,
            )
            lines.append("f " + " ".join(f"{i}/{i}/{i}" for i in indices))

    return "\n".join(lines) + "\n"


def generate_rend(index: int) -> str:
    data = {
        "lodList": [
            {
                "mesh": f"$CONTENT_DATA/Renderable/curve_tubes/Models/curve_tube_{index:02d}.obj",
                "subMeshList": [{"material": "ConnectJoint", "textureList": []}],
            }
        ]
    }
    return json.dumps(data, indent=4) + "\n"


def write_lua(tiers):
    lines = [
        "-- Generated by Renderable/curve_tubes/generate_curve_tubes.py.",
        "CurveTubeModels = {",
    ]
    for index, length, shape_uuid in tiers:
        lines.append(
            f'    {{ length = {length:.9f}, uuid = sm.uuid.new("{shape_uuid}") }},'
        )
    lines.append("}")
    lines.append("")
    LUA_PATH.write_text("\n".join(lines), encoding="utf-8")


def update_shapeset(tiers):
    data = json.loads(SHAPESET_PATH.read_text(encoding="utf-8"))
    parts = [
        part
        for part in data["partList"]
        if not part.get("renderable", "").startswith(RENDERABLE_PREFIX)
    ]
    for index, _, shape_uuid in tiers:
        parts.append(
            {
                "box": {"x": 1, "y": 1, "z": 1},
                "color": "ffffff",
                "renderable": f"{RENDERABLE_PREFIX}{index:02d}.rend",
                "uuid": shape_uuid,
                "showInInventory": False,
            }
        )
    data["partList"] = parts
    SHAPESET_PATH.write_text(json.dumps(data, indent=4) + "\n", encoding="utf-8")


def main():
    MODEL_DIR.mkdir(parents=True, exist_ok=True)
    REND_DIR.mkdir(parents=True, exist_ok=True)
    for path in MODEL_DIR.glob("curve_tube_*.obj"):
        path.unlink()
    for path in REND_DIR.glob("curve_tube_*.rend"):
        path.unlink()

    tiers = []
    for index, length in enumerate(tier_lengths()):
        shape_uuid = tier_uuid(index, length)
        tiers.append((index, length, shape_uuid))
        (MODEL_DIR / f"curve_tube_{index:02d}.obj").write_text(
            generate_obj(length), encoding="utf-8"
        )
        (REND_DIR / f"curve_tube_{index:02d}.rend").write_text(
            generate_rend(index), encoding="utf-8"
        )

    write_lua(tiers)
    update_shapeset(tiers)
    print(f"Generated {len(tiers)} curve tube tiers from {tiers[0][1]} to {tiers[-1][1]} units")


if __name__ == "__main__":
    main()
